using System;
using System.Collections.Generic;
using SpotifyAPI.Web.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace youShouldCheckOutThisBand.Entities
{
    public class AlbumCoverEntity:Image
    {
        /// <summary>
        /// this is autogenerated since images in spotify dont have spotify ids
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public new int Id { get; set; }
       
        public virtual AlbumEntity Album { get; set; }
    }
}
